name: Release Workflow

on:
    # Triggers the workflow after the Test Workflow has completed
    workflow_run:
        workflows: ['Test Workflow']
        types:
            - completed
        branches:
            - main
    # Allows you to run this workflow manually from the Actions tab
    workflow_dispatch:

jobs:
    release:
        runs-on: ubuntu-latest
        environment: release
        if: ${{ github.event.workflow_run.conclusion == 'success' }}
        steps:
            - uses: actions/setup-node@v3
              with:
                  node-version: '16.x'
                  registry-url: 'https://registry.npmjs.org'
            - uses: actions/checkout@v3
            - uses: actions/cache@v3
              with:
                  path: ~/.npm
                  key: npm-node-${{ hashFiles('**/package-lock.json') }}
                  restore-keys: |
                      npm-node-
            - name: Install Deps
              run: npm ci --ignore-scripts
            - name: Build
              run: npm run build
            - run: npm publish
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
