name: Test Workflow

on:
    # Triggers the workflow on push events
    push:
    # Triggers the workflow on pull request events
    pull_request:
    # Allows you to run this workflow manually from the Actions tab
    workflow_dispatch:

permissions:
    contents: read

jobs:
    test:
        runs-on: ubuntu-latest
        name: 'Run tests'
        steps:
            - uses: actions/setup-node@v3
            - uses: actions/checkout@v3
            - uses: actions/cache@v3
              with:
                  path: ~/.npm
                  key: npm-node-${{ hashFiles('**/package-lock.json') }}
                  restore-keys: |
                      npm-node-
            - name: Install Deps
              run: npm ci --ignore-scripts
            - name: Run Tests
              run: npm run test
